"""Subscription rule evaluation: shape validation, matching, explained decisions.

This package is the rule sub-block of the platform media feature. It is import-safe and side-effect
free: importing it starts no process, opens no file, reads no clock and touches no database. The
only thing in the whole package that ever leaves the process is the dedicated regex child, and it is
started per request by :class:`RuleEvaluator` — never at import time and never globally.

Public surface:

* :func:`parse_policy` — pure structural validation of one policy document, plus its digest;
* :class:`RuleEvaluator` — an async context manager owning the bounded resources, with
  ``validate_policy`` (structure **and** real regex compilation) and ``evaluate`` (one explained
  decision);
* the frozen value types and the two named errors.

Deliberately absent: any queue, database, HTTP route, web surface, download engine, account access
or scheduler. Those belong to the tasks that consume this block.
"""

from .evaluator import MAX_CONCURRENT_REQUESTS, RuleEvaluator
from .matching import (
    FIELD_PROJECTION_MAX_BYTES,
    PLAIN_OPS,
    any_value_matches,
    compare,
    field_values,
    projection_within_budget,
)
from .policy import parse_policy, policy_digest, regex_rules
from .regex_process import (
    CALL_TIMEOUT_SECONDS,
    CLEANUP_TIMEOUT_SECONDS,
    IPC_MAX_REQUEST_BYTES,
    IPC_MAX_RESPONSE_BYTES,
    REQUEST_TIMEOUT_SECONDS,
    STARTUP_TIMEOUT_SECONDS,
    RegexWorker,
    worker_script_path,
)
from .types import (
    DECISIONS,
    DECISION_DOWNLOAD,
    DECISION_RULE_ERROR,
    DECISION_SKIP,
    DOCUMENT_FIELDS,
    ERROR_CLOSED,
    ERROR_DUPLICATE_GROUP_ID,
    ERROR_DUPLICATE_RULE_ID,
    ERROR_EMPTY_RULES,
    ERROR_INVALID_ACCESSIBLE,
    ERROR_INVALID_CASE_SENSITIVE,
    ERROR_INVALID_DOCUMENT,
    ERROR_INVALID_FIELD_NAME,
    ERROR_INVALID_GROUP,
    ERROR_INVALID_GROUP_ID,
    ERROR_INVALID_GROUP_LIST,
    ERROR_INVALID_METADATA,
    ERROR_INVALID_OP,
    ERROR_INVALID_QUALITY_SATISFIED,
    ERROR_INVALID_REGEX,
    ERROR_INVALID_REVISION,
    ERROR_INVALID_RULE,
    ERROR_INVALID_RULE_ID,
    ERROR_INVALID_RULES,
    ERROR_INVALID_SCHEMA_VERSION,
    ERROR_INVALID_SNAPSHOT_REVISION,
    ERROR_INVALID_VALUE,
    ERROR_MISSING_FIELD,
    ERROR_TOO_MANY_GROUPS,
    ERROR_TOO_MANY_RULES,
    ERROR_UNKNOWN_FIELD,
    ERROR_VALUE_TOO_LONG,
    EVALUATION_ERROR_CODES,
    FAILURE_REASONS,
    FIELDS,
    FIELD_DESCRIPTION,
    FIELD_TAGS,
    FIELD_TITLE,
    FIELD_UPLOADER_ID,
    FIELD_UPLOADER_NAME,
    GROUPS_MAX,
    GROUP_FIELDS,
    LIST_BLACKLIST,
    LIST_WHITELIST,
    NORMAL_REASONS,
    OPS,
    OP_CONTAINS,
    OP_EQUALS,
    OP_PREFIX,
    OP_REGEX,
    OP_SUFFIX,
    POLICY_ERROR_CODES,
    REASONS,
    REASON_BLACKLIST_MATCH,
    REASON_BUSY,
    REASON_ELIGIBLE,
    REASON_EVALUATION_TIMEOUT,
    REASON_INACCESSIBLE,
    REASON_INPUT_TOO_LARGE,
    REASON_QUALITY_SATISFIED,
    REASON_REGEX_TIMEOUT,
    REASON_REGEX_WORKER_FAILED,
    REASON_WHITELIST_NO_MATCH,
    REGEX_OPS,
    REGEX_VALUE_MAX,
    RESULTS,
    RESULT_ERROR,
    RESULT_MATCHED,
    RESULT_NOT_EVALUATED,
    RESULT_NOT_MATCHED,
    REVISION_MAX,
    REVISION_MIN,
    RULE_FIELDS,
    RULES_PER_GROUP_MAX,
    RULES_PER_GROUP_MIN,
    SCHEMA_VERSION,
    TRACE_BLACKLIST_MATCHED,
    TRACE_ERROR_SHORT_CIRCUIT,
    TRACE_PRIORITY_SHORT_CIRCUIT,
    TRACE_RULE_SHORT_CIRCUIT,
    TRACE_WHITELIST_MATCHED,
    VALUE_MAX,
    Group,
    GroupTrace,
    Rule,
    RuleDecision,
    RuleEvaluationError,
    RulePolicy,
    RuleTrace,
    RuleValidationError,
)

__all__ = [
    "CALL_TIMEOUT_SECONDS",
    "CLEANUP_TIMEOUT_SECONDS",
    "DECISIONS",
    "DECISION_DOWNLOAD",
    "DECISION_RULE_ERROR",
    "DECISION_SKIP",
    "DOCUMENT_FIELDS",
    "ERROR_CLOSED",
    "ERROR_DUPLICATE_GROUP_ID",
    "ERROR_DUPLICATE_RULE_ID",
    "ERROR_EMPTY_RULES",
    "ERROR_INVALID_ACCESSIBLE",
    "ERROR_INVALID_CASE_SENSITIVE",
    "ERROR_INVALID_DOCUMENT",
    "ERROR_INVALID_FIELD_NAME",
    "ERROR_INVALID_GROUP",
    "ERROR_INVALID_GROUP_ID",
    "ERROR_INVALID_GROUP_LIST",
    "ERROR_INVALID_METADATA",
    "ERROR_INVALID_OP",
    "ERROR_INVALID_QUALITY_SATISFIED",
    "ERROR_INVALID_REGEX",
    "ERROR_INVALID_REVISION",
    "ERROR_INVALID_RULE",
    "ERROR_INVALID_RULE_ID",
    "ERROR_INVALID_RULES",
    "ERROR_INVALID_SCHEMA_VERSION",
    "ERROR_INVALID_SNAPSHOT_REVISION",
    "ERROR_INVALID_VALUE",
    "ERROR_MISSING_FIELD",
    "ERROR_TOO_MANY_GROUPS",
    "ERROR_TOO_MANY_RULES",
    "ERROR_UNKNOWN_FIELD",
    "ERROR_VALUE_TOO_LONG",
    "EVALUATION_ERROR_CODES",
    "FAILURE_REASONS",
    "FIELDS",
    "FIELD_DESCRIPTION",
    "FIELD_PROJECTION_MAX_BYTES",
    "FIELD_TAGS",
    "FIELD_TITLE",
    "FIELD_UPLOADER_ID",
    "FIELD_UPLOADER_NAME",
    "GROUPS_MAX",
    "GROUP_FIELDS",
    "Group",
    "GroupTrace",
    "IPC_MAX_REQUEST_BYTES",
    "IPC_MAX_RESPONSE_BYTES",
    "LIST_BLACKLIST",
    "LIST_WHITELIST",
    "MAX_CONCURRENT_REQUESTS",
    "NORMAL_REASONS",
    "OPS",
    "OP_CONTAINS",
    "OP_EQUALS",
    "OP_PREFIX",
    "OP_REGEX",
    "OP_SUFFIX",
    "PLAIN_OPS",
    "POLICY_ERROR_CODES",
    "REASONS",
    "REASON_BLACKLIST_MATCH",
    "REASON_BUSY",
    "REASON_ELIGIBLE",
    "REASON_EVALUATION_TIMEOUT",
    "REASON_INACCESSIBLE",
    "REASON_INPUT_TOO_LARGE",
    "REASON_QUALITY_SATISFIED",
    "REASON_REGEX_TIMEOUT",
    "REASON_REGEX_WORKER_FAILED",
    "REASON_WHITELIST_NO_MATCH",
    "REGEX_OPS",
    "REGEX_VALUE_MAX",
    "REQUEST_TIMEOUT_SECONDS",
    "RESULTS",
    "RESULT_ERROR",
    "RESULT_MATCHED",
    "RESULT_NOT_EVALUATED",
    "RESULT_NOT_MATCHED",
    "REVISION_MAX",
    "REVISION_MIN",
    "RULE_FIELDS",
    "RULES_PER_GROUP_MAX",
    "RULES_PER_GROUP_MIN",
    "RegexWorker",
    "Rule",
    "RuleDecision",
    "RuleEvaluationError",
    "RuleEvaluator",
    "RulePolicy",
    "RuleTrace",
    "RuleValidationError",
    "SCHEMA_VERSION",
    "STARTUP_TIMEOUT_SECONDS",
    "TRACE_BLACKLIST_MATCHED",
    "TRACE_ERROR_SHORT_CIRCUIT",
    "TRACE_PRIORITY_SHORT_CIRCUIT",
    "TRACE_RULE_SHORT_CIRCUIT",
    "TRACE_WHITELIST_MATCHED",
    "VALUE_MAX",
    "any_value_matches",
    "compare",
    "field_values",
    "parse_policy",
    "policy_digest",
    "projection_within_budget",
    "regex_rules",
    "worker_script_path",
]
