"""Platform media domain: Bilibili identity, metadata normalization and sidecar candidates.

This package is a pure, import-safe block. Importing it performs no IO, starts no process, creates
no directory, reads no clock and owns no database: TS-090 only turns an internal projection into
normalized metadata and then into in-memory NFO/source.json candidates.

The public surface is deliberately two functions and their frozen value types plus two named errors.
Anything else a caller needs (keys, canonical links, layout names) is reachable through the returned
records, so no caller has to reimplement identity or path rules.
"""

from .metadata import normalize_bilibili
from .sidecars import render_sidecars
from .types import (
    FIELD_SOURCE_NAMES,
    GENERATOR,
    IMAGE_EXTENSIONS,
    IMAGE_ROLES,
    ISSUE_AUTHOR_NAME_MISSING,
    ISSUE_CODES,
    ISSUE_COVER_LOCAL_MISSING,
    ISSUE_COVER_SOURCE_MISSING,
    ISSUE_CREATOR_MISSING,
    ISSUE_DESCRIPTION_MISSING,
    ISSUE_PART_TITLE_MISSING,
    ISSUE_PUBLISHED_AT_MISSING,
    ISSUE_TITLE_MISSING,
    LAYOUTS,
    LAYOUT_MULTIPART,
    LAYOUT_SINGLE,
    MEDIA_EXTENSIONS,
    NFO_EPISODEDETAILS,
    NFO_MOVIE,
    NFO_TVSHOW,
    NFO_XML_DECLARATION,
    PROVIDER,
    ROLE_COLLABORATOR,
    ROLE_LABELS,
    ROLE_UPLOADER,
    SCHEMA_VERSION,
    SEASON_DIRECTORY,
    SOURCE_MISSING,
    SOURCE_SOURCE,
    SOURCE_USER,
    STATUS_RENDERED_UNVERIFIED,
    CreatorEntry,
    ExpectedMedia,
    ImageBinding,
    Issue,
    MediaMetadata,
    MetadataValidationError,
    PartEntry,
    ReferencedImage,
    RenderRequest,
    RenderRequestError,
    SidecarBundle,
    SidecarFile,
)

__all__ = [
    "FIELD_SOURCE_NAMES",
    "GENERATOR",
    "IMAGE_EXTENSIONS",
    "IMAGE_ROLES",
    "ISSUE_AUTHOR_NAME_MISSING",
    "ISSUE_CODES",
    "ISSUE_COVER_LOCAL_MISSING",
    "ISSUE_COVER_SOURCE_MISSING",
    "ISSUE_CREATOR_MISSING",
    "ISSUE_DESCRIPTION_MISSING",
    "ISSUE_PART_TITLE_MISSING",
    "ISSUE_PUBLISHED_AT_MISSING",
    "ISSUE_TITLE_MISSING",
    "LAYOUTS",
    "LAYOUT_MULTIPART",
    "LAYOUT_SINGLE",
    "MEDIA_EXTENSIONS",
    "NFO_EPISODEDETAILS",
    "NFO_MOVIE",
    "NFO_TVSHOW",
    "NFO_XML_DECLARATION",
    "PROVIDER",
    "ROLE_COLLABORATOR",
    "ROLE_LABELS",
    "ROLE_UPLOADER",
    "SCHEMA_VERSION",
    "SEASON_DIRECTORY",
    "SOURCE_MISSING",
    "SOURCE_SOURCE",
    "SOURCE_USER",
    "STATUS_RENDERED_UNVERIFIED",
    "CreatorEntry",
    "ExpectedMedia",
    "ImageBinding",
    "Issue",
    "MediaMetadata",
    "MetadataValidationError",
    "PartEntry",
    "ReferencedImage",
    "RenderRequest",
    "RenderRequestError",
    "SidecarBundle",
    "SidecarFile",
    "normalize_bilibili",
    "render_sidecars",
]
