"""The production static container: what can be proven here, and what is explicitly not proven.

This suite never claims a container works because a Dockerfile exists. Everything it can check
without a container runtime - the image definition, the ignore rules, the deployment template, and
the console served from the built assets - it checks against the real files. Everything that needs
a container runtime is skipped with a reason and is reported as unverified in the handoff.
"""

import json
import os
import re
import shutil
import ssl
import subprocess
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

import aiohttp

from runtime_fixture import (
    READY_TOKEN,
    READY_TOKEN_ENV,
    environment,
    read_events,
    runtime_settings,
    start_server,
)

from services.platform import diagnostics, diagnostics_config, runtime_health
from services.platform.server import create_app
from services.platform.service import Platform

ROOT = Path(__file__).resolve().parents[2]
DOCKERFILE = ROOT / "Dockerfile"
DOCKERIGNORE = ROOT / ".dockerignore"
SETTINGS_EXAMPLE = ROOT / "deploy" / "platform" / "settings.example.json"
DEPLOYMENT_DOC = ROOT / "docs" / "platform" / "deployment.md"
# The repository's own build output, produced by `npm run build` outside the image.
WEB_BUILD = ROOT / "apps" / "web" / "dist"

# A value that looks like a baked credential: long, high-entropy and not an obvious placeholder.
SECRET_SHAPED = re.compile(r"(?:[A-Fa-f0-9]{32,}|[A-Za-z0-9+/]{40,}={0,2})")


def docker_available():
    return shutil.which("docker") is not None


def web_build_available():
    return (WEB_BUILD / "index.html").is_file()


def _hash(password):
    """The product's own verifier format, generated by the product's own helper."""
    from services.platform.web_console import password_hash

    return password_hash(password, salt=b"\x00" * 16)


class ImageDefinitionTests(unittest.TestCase):
    """Static facts about the image definition: true whether or not a runtime is installed."""

    def setUp(self):
        self.text = DOCKERFILE.read_text(encoding="utf-8")
        self.lines = [
            line.strip()
            for line in self.text.splitlines()
            if line.strip() and not line.startswith("#")
        ]
        self.ignored = [
            line.strip()
            for line in DOCKERIGNORE.read_text(encoding="utf-8").splitlines()
            if line.strip() and not line.startswith("#")
        ]

    def test_the_image_definition_exists_and_pins_its_base(self):
        self.assertTrue(DOCKERFILE.is_file())
        froms = [line for line in self.lines if line.startswith("FROM ")]
        self.assertEqual(len(froms), 1)
        self.assertTrue(froms[0].startswith("FROM python:3.12."), froms[0])
        self.assertNotIn(":latest", self.text)
        self.assertNotIn("python:3-slim", self.text)

    def test_the_service_never_runs_as_root(self):
        self.assertIn("USER 10001:10001", self.text)
        self.assertNotRegex(self.text, r"USER\s+root")
        self.assertIn("useradd", self.text)

    def test_no_secret_is_read_or_baked_at_build_time(self):
        for forbidden in ("ARG ", "ENV TOKEN", "ENV SECRET", "ENV PASSWORD", "COPY .env"):
            self.assertNotIn(forbidden, self.text, forbidden)
        self.assertNotIn("COPY . ", self.text)
        self.assertNotIn("COPY .\n", self.text)
        self.assertNotIn("--build-arg", self.text)

    def test_only_the_reviewed_source_tree_is_copied_in(self):
        copies = [line for line in self.lines if line.startswith("COPY ")]
        self.assertTrue(copies)
        for line in copies:
            source = line.split()[1]
            self.assertIn(
                source,
                ("pyproject.toml", "services/", "contracts/", "apps/web/dist/"),
                source,
            )
        self.assertIn("COPY contracts/ ./contracts/", self.text)
        self.assertIn("COPY apps/web/dist/ ./web/", self.text)

    def test_dependencies_come_from_the_project_metadata_only(self):
        # A second pin list in the Dockerfile would drift from pyproject.toml, so the image must
        # install the project itself and never restate a version.
        self.assertIn("RUN python -m pip install --no-compile .", self.text)
        installs = [line for line in self.lines if "pip install" in line]
        self.assertEqual(len(installs), 1)
        for name in ("aiohttp", "jsonschema", "referencing", "ruff"):
            self.assertNotIn(name, self.text, name)

    def test_the_image_carries_no_build_tooling_into_the_runtime(self):
        for forbidden in ("apt-get", "curl ", "wget ", "gcc", "node", "npm", "make"):
            self.assertNotIn(forbidden, self.text, forbidden)
        self.assertIn("PYTHONDONTWRITEBYTECODE=1", self.text)

    def test_liveness_is_checked_over_verified_tls(self):
        healthcheck = self.text[self.text.index("HEALTHCHECK") :]
        self.assertIn("/health/live", healthcheck)
        self.assertIn("create_default_context", healthcheck)
        self.assertIn("cafile=", healthcheck)
        # A readiness check needs a credential the orchestrator would have to hold; liveness does
        # not, and only liveness may decide whether to restart the process.
        self.assertNotIn("/health/ready", healthcheck)

    def test_the_entry_point_is_the_serve_command_on_the_declared_port(self):
        self.assertIn('ENTRYPOINT ["python", "-m", "services.platform"]', self.text)
        self.assertIn('CMD ["--settings", "/etc/tianshu/settings.json", "serve"', self.text)
        self.assertIn('--port", "8443', self.text)
        self.assertIn("EXPOSE 8443", self.text)
        self.assertIn('--host", "0.0.0.0', self.text)
        self.assertIn("STOPSIGNAL SIGTERM", self.text)

    def test_state_and_logs_are_declared_as_volumes_outside_the_image(self):
        self.assertIn('VOLUME ["/var/lib/tianshu", "/var/log/tianshu"]', self.text)
        self.assertIn("chown -R 10001:10001 /var/lib/tianshu /var/log/tianshu", self.text)

    def test_the_ignore_rules_keep_secrets_and_local_state_out(self):
        for pattern in (
            ".git",
            ".runtime",
            "node_modules",
            "tests",
            "*.sqlite",
            "*.pem",
            "*.key",
            ".env",
        ):
            self.assertIn(pattern, self.ignored, pattern)

    def test_the_ignore_rules_never_drop_what_the_image_must_carry(self):
        # `apps/web/dist` is copied by the Dockerfile, so ignoring it would break the build; and the
        # frozen contract's own README is covered by its manifest, so ignoring markdown would make
        # the readiness check fail on a file that should have been shipped.
        for pattern in ("apps/web/dist", "dist", "*.md", "README.md", "contracts"):
            self.assertNotIn(pattern, self.ignored, pattern)

    def test_a_build_that_is_not_verified_is_not_claimed_as_verified(self):
        # The definition must not pretend a container was built or run: it says so in its own text,
        # and this suite records the same fact as a skip rather than a pass.
        self.assertIn("not the same as proving the deployment works", self.text)


class DeploymentTemplateTests(unittest.TestCase):
    def setUp(self):
        self.raw = SETTINGS_EXAMPLE.read_text(encoding="utf-8")
        self.settings = json.loads(self.raw)

    def test_the_template_is_valid_json_with_the_reviewed_shape(self):
        self.assertEqual(self.settings["mode"], "service_https")
        self.assertEqual(self.settings["storage"], "sqlite_local")
        for key in (
            "database_path",
            "contract_directory",
            "principals",
            "entries",
            "providers",
            "web",
            "tls",
        ):
            self.assertIn(key, self.settings, key)

    def test_the_template_holds_no_credential_of_its_own(self):
        # Every credential is a variable *name* the process reads at run time. A literal secret in a
        # template is a secret in the repository and in every copy of it.
        for section in ("principals",):
            for principal in self.settings[section].values():
                self.assertTrue(principal["token_env"].isupper(), principal["token_env"])
                self.assertNotIn("token", set(principal) - {"token_env"})
        self.assertNotIn("password", self.settings["web"])
        self.assertNotIn("token", self.settings["web"])
        for match in SECRET_SHAPED.finditer(self.raw):
            value = match.group(0)
            self.assertTrue(
                set(value) <= {"0"} or value.startswith("replace-"),
                "a value that looks like a baked secret: " + value[:16],
            )

    def test_every_path_in_the_template_is_absolute_and_inside_the_image_layout(self):
        self.assertTrue(self.settings["database_path"].startswith("/var/lib/tianshu/"))
        self.assertTrue(self.settings["contract_directory"].startswith("/srv/tianshu/contracts/"))
        self.assertTrue(self.settings["web"]["static_directory"].startswith("/srv/tianshu/"))
        for key in ("certificate_file", "private_key_file"):
            self.assertTrue(self.settings["tls"][key].startswith("/etc/tianshu/tls/"), key)

    def test_the_diagnostics_section_is_the_reviewed_one(self):
        section = self.settings["diagnostics"]
        self.assertEqual(
            set(section),
            {"contract_directory", "log_directory", "log_directory_bytes", "ready_token_env"},
        )
        self.assertEqual(section["ready_token_env"], READY_TOKEN_ENV)
        self.assertEqual(section["log_directory"], "/var/log/tianshu")
        self.assertEqual(section["contract_directory"], "/srv/tianshu/contracts/diagnostics/v1")
        self.assertGreaterEqual(section["log_directory_bytes"], diagnostics.MIN_DIRECTORY_BYTES)
        self.assertLessEqual(section["log_directory_bytes"], diagnostics.MAX_DIRECTORY_BYTES)
        # The parser demands an absolute path *on the machine that runs it*, and this template
        # targets a Linux container, so it is validated here against the host's own absolute form.
        with tempfile.TemporaryDirectory() as directory:
            diagnostics_config.parse_diagnostics_settings(
                {
                    "diagnostics": {
                        **section,
                        "contract_directory": os.environ["TS100_DIAGNOSTICS_CONTRACT_DIR"],
                        "log_directory": str(Path(directory) / "logs"),
                    }
                }
            )

    def test_the_readiness_credential_is_not_any_business_credential(self):
        names = {principal["token_env"] for principal in self.settings["principals"].values()}
        self.assertNotIn(self.settings["diagnostics"]["ready_token_env"], names)

    def test_the_template_matches_what_the_entry_point_actually_accepts(self):
        # A template is only useful if its key set is the key set the product reads. This fills the
        # placeholders the way an operator would and requires the composition root to assemble: an
        # unknown or renamed key is refused at assembly, so this is a real claim, not a comment.
        import copy

        with tempfile.TemporaryDirectory() as directory:
            filled = copy.deepcopy(self.settings)
            filled["database_path"] = str(Path(directory) / "platform.sqlite")
            filled["contract_directory"] = os.environ["TS012_CONTRACT_DIR"]
            filled["diagnostics"] = {
                "contract_directory": os.environ["TS100_DIAGNOSTICS_CONTRACT_DIR"],
                "log_directory": str(Path(directory) / "logs"),
            }
            filled["web"]["static_directory"] = str(Path(directory) / "web")
            filled["web"]["origin"] = "https://platform.example.invalid"
            filled["web"]["username"] = "operator"
            filled["web"]["password_hash"] = _hash("synthetic-operator-password")
            filled["principals"]["admin"]["account"]["immutable_account_id"] = "local-operator"
            filled["entries"]["config-entry"]["account"]["immutable_account_id"] = "local-operator"
            filled["entries"]["config-entry"]["channel"]["binding_id"] = "local-management"
            filled["entries"]["config-entry"]["actor_id"] = "actor-config"
            Path(filled["web"]["static_directory"]).mkdir(parents=True, exist_ok=True)
            (Path(filled["web"]["static_directory"]) / "index.html").write_text(
                '<!doctype html><div id="root"></div>', encoding="utf-8"
            )
            platform = Platform(filled)
            self.addCleanup(platform.close)
        self.assertTrue(platform.health.sidecars == () or platform.health.sidecars)


class ContainerRuntimeTests(unittest.TestCase):
    """Everything that needs a container runtime, and therefore an explicit skip here."""

    @unittest.skipUnless(
        docker_available(), "docker is not installed; image build and run unverified"
    )
    def test_the_image_builds_from_the_reviewed_context(self):
        result = subprocess.run(
            ["docker", "build", "--tag", "tianshu-platform:ts100-verify", str(ROOT)],
            capture_output=True,
            text=True,
            timeout=1800,
        )
        self.assertEqual(result.returncode, 0, result.stderr[-4000:])

    @unittest.skipUnless(docker_available(), "docker is not installed; container run unverified")
    def test_the_container_starts_reads_ready_and_stops_on_sigterm(self):
        self.fail(
            "run the documented rollout from docs/platform/deployment.md and record the result"
        )

    @unittest.skipUnless(docker_available(), "docker is not installed; container TLS unverified")
    def test_the_container_serves_verified_tls_and_its_healthcheck_passes(self):
        self.fail("assert the container healthcheck and a real TLS probe against the running image")

    @unittest.skipUnless(docker_available(), "docker is not installed; preflight unverified")
    def test_a_one_shot_preflight_container_creates_nothing(self):
        self.fail("assert the preflight container leaves the mounted data directory untouched")


@unittest.skipUnless(
    web_build_available(), "apps/web/dist is not built; the served console is unverified"
)
class ServedConsoleTests(unittest.IsolatedAsyncioTestCase):
    """The console as the container actually serves it: the real build, over real TLS."""

    async def asyncSetUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.env = patch.dict(os.environ, environment(), clear=False)
        self.env.start()
        self.addCleanup(self.env.stop)
        self.addCleanup(diagnostics.reset)
        self.settings = runtime_settings(self.temp.name, static=str(WEB_BUILD))
        self.platform = Platform(self.settings)
        self.sink = diagnostics.Diagnostics(self.settings["diagnostics"]["log_directory"])
        diagnostics.activate(self.sink)
        self.addCleanup(self.sink.close, 2.0)
        context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
        context.load_cert_chain(
            self.settings["tls"]["certificate_file"], self.settings["tls"]["private_key_file"]
        )
        self.runner, self.url = await start_server(create_app(self.platform), tls=context)
        self.addAsyncCleanup(self.runner.cleanup)
        # The console refuses any request whose Host is not its configured origin - that guard is
        # the point of the same-origin console, so the test tells the deployment the origin it was
        # actually reached on rather than weakening the guard.
        self.platform.settings["web"]["origin"] = self.url
        self.client = aiohttp.ClientSession(
            trust_env=False,
            timeout=aiohttp.ClientTimeout(total=10),
            connector=aiohttp.TCPConnector(
                ssl=ssl.create_default_context(cafile=self.settings["tls"]["certificate_file"])
            ),
        )
        self.addAsyncCleanup(self.client.close)

    async def test_the_real_build_is_served_with_the_documented_security_headers(self):
        async with self.client.get(self.url + "/") as response:
            self.assertEqual(response.status, 200)
            self.assertIn("frame-ancestors 'none'", response.headers["Content-Security-Policy"])
            self.assertEqual(response.headers["X-Content-Type-Options"], "nosniff")
            body = await response.text()
        self.assertIn('<div id="root"', body)

    async def test_the_entry_points_own_assets_are_really_served(self):
        async with self.client.get(self.url + "/") as response:
            html = await response.text()
        references = runtime_health.ASSET_REFERENCE.findall(html)
        self.assertTrue(references, "the built entry point references no asset")
        for reference in references:
            async with self.client.get(self.url + reference) as response:
                self.assertEqual(response.status, 200, reference)
                self.assertTrue(await response.read())

    async def test_the_static_container_needs_no_database_and_no_contract_to_answer_liveness(self):
        async with self.client.get(self.url + "/health/live") as response:
            self.assertEqual(response.status, 200)
            self.assertEqual(await response.json(), {"status": "alive"})

    async def test_a_client_without_the_readiness_credential_learns_nothing(self):
        async with self.client.get(self.url + "/health/ready") as response:
            self.assertEqual(response.status, 401)
            self.assertEqual(await response.json(), {"code": "unauthorized"})

    async def test_an_unknown_path_is_not_a_directory_listing(self):
        for path in ("/../Dockerfile", "/deploy/platform/settings.example.json", "/.git/config"):
            async with self.client.get(self.url + path) as response:
                self.assertIn(response.status, (400, 403, 404), path)
                self.assertNotIn("scrypt-v1", await response.text())

    async def test_the_console_is_served_over_verified_tls_and_stays_ready(self):
        async with self.client.get(
            self.url + "/health/ready", headers={"Authorization": "Bearer " + READY_TOKEN}
        ) as response:
            document = await response.json()
        self.assertEqual(response.status, 200, document)
        self.assertEqual(document["checks"]["web_static"], "ok")
        self.assertEqual(document["status"], "ready")

    async def test_serving_the_console_is_logged_once_and_probes_are_not_logged_at_all(self):
        await self.client.get(self.url + "/health/live")
        await self.client.get(self.url + "/health/live")
        await self.client.get(self.url + "/")
        self.sink.flush()
        events = read_events(self.settings["diagnostics"]["log_directory"])
        names = [record["event"] for record in events]
        # Every business request is registered in full and never sampled; the two probe requests
        # above left nothing behind, because a probe that logged would be a probe that writes.
        self.assertEqual(names.count("http.request.started"), 1)
        self.assertEqual(names.count("http.request.finished"), 1)
        for record in events:
            self.assertNotIn("/health/", json.dumps(record))


class DocumentationTests(unittest.TestCase):
    """The rollout a reviewer would follow must match the artifact it describes."""

    def setUp(self):
        if not DEPLOYMENT_DOC.is_file():
            self.skipTest("docs/platform/deployment.md is not written yet")
        self.doc = DEPLOYMENT_DOC.read_text(encoding="utf-8")
        self.dockerfile = DOCKERFILE.read_text(encoding="utf-8")

    def test_the_documented_commands_name_the_real_artifact(self):
        self.assertIn("docker build", self.doc)
        self.assertIn("docker run", self.doc)
        self.assertIn("preflight", self.doc)

    def test_the_documented_port_and_health_paths_match_the_image(self):
        self.assertIn("8443", self.doc)
        self.assertIn("/health/live", self.doc)
        self.assertIn("/health/ready", self.doc)
        self.assertIn("8443", self.dockerfile)

    def test_the_documented_readiness_credential_is_the_one_the_image_reads(self):
        self.assertIn(READY_TOKEN_ENV, self.doc)
        self.assertIn(READY_TOKEN_ENV, self.dockerfile + SETTINGS_EXAMPLE.read_text("utf-8"))

    def test_the_rollout_is_explicit_about_what_was_not_executed_here(self):
        self.assertIn("未验证", self.doc)
        self.assertIn("needs_validation", self.doc)

    def test_the_documented_log_and_data_paths_are_the_mounted_volumes(self):
        for path in ("/var/lib/tianshu", "/var/log/tianshu", "/etc/tianshu"):
            self.assertIn(path, self.doc, path)
            self.assertIn(path, self.dockerfile, path)
